def display_menu():
    print("\n" + "=" * 50)
    print("         MENÚ PRINCIPAL")
    print("=" * 50)
    print("1. Guardar datos de persona")
    print("2. Listar personas ingresadas")
    print("3. Buscar personas por nombre")
    print("4. Buscar personas por aprox. direccion")
    print("5. Salir")
    print("=" * 50)